### PR TITLE
Sync with Dragonfly base

### PR DESCRIPTION
**Pull request by saeranv**

### CODE REVIEW

**Comment by chriswmackey** [comment]
@saeranv ,

This is on mt to do list for this weekend.  Thanks for taking a stab at this.  The new UWG takes input files in a different format and so a lot of changes are needed.

-Chris

**Comment by saeranv** [comment]
Hey @chriswmackey, sorry this was an accidental pull request while I was trying to play around with some older edits I worked on a couple of months ago. Best just to ignore it. 

But, the reason I've been messing around with the code is because I've been trying to hunt down an error I've been having with the Dragonfly example GH script you posted: https://github.com/chriswmackey/hydra_2/commit/88dafb045922e4855949a1aeb7060b283b9ee651

I'm getting an error saying the UWGEngine isn't writing the transformed epw file: 
run_uwg_error

This is using the UWGEngine.exe , so I feel like it shouldn't have anything to do with the new input file format that you're talking about for the new UWG. Any idea why this is happening? 

-S

**Comment by chriswmackey** [comment]
@saeranv ,
That example file works on my machine so it must have something to do with your version of UWG installed. Remeber these components need the older version of UWG and don't work with the new one.  Just to be sure, does the working directory contain any files in it after running the component?

**Comment by saeranv** [comment]
Thanks @chriswmackey. So I didn't download a new UWG, it's using the version that Dragonfly installs/comes with (which is UWGEngine.exe). Currently I'm using the 64 bit R2015b (9.0) Matlab runtime, and the 0.064 and 0.061 versions of LB and HB respectively. 

With regards to the working directories, the main Dragonfly folder has files in it after running:

working_df_1
And here's the working folder created for the Run UWG component:

working_df
So far I've tried uninstalling and installing the components and updating LB/HB, and switching between the 32-bit, and 64-bit MATLAB runtime. Nothing's working so far. Any further thoughts?

-S

**Comment by chriswmackey** [comment]
@saeranv ,
This older version of the UWG is meant to run the 32-bit Matlab compiler so keep using that one.
Do you get any command prompt windows popping up like this:
image

If so, than just try unplugging the analysisPeriod from the Run UWG component.  It seems to be that it's running but it's adding the analysis period to the name of the weather file.

If that doesn't fix it, then we know it's an issue with your matlab/UWG version and not the Dragonfly component.

-Chris

**Comment by chriswmackey** [comment]
@saeranv ,
I think I discovered what was stopping you previously and I believe that I have fixed it with these commits:
https://github.com/chriswmackey/Dragonfly/commit/30089cd1f832623d4d6b0818ca9f601d28e3b9a2
https://github.com/hansukyang/UWG_Matlab/commit/3f1ca09ce27a1056fab91cfa8130c3128bc85f2f

If you follow the instructions at the end of this discussion, I think that you should be able to run the UWG without issue:
http://www.grasshopper3d.com/group/ladybug/forum/topics/problem-with-drangonfly-and-urban-weather-generator?commentId=2985220%3AComment%3A1730867&xg_source=msg_com_gr_forum

Let me know if you get the chance to try it out.
-Chris

**Comment by saeranv** [comment]
Thanks @chriswmackey , unfortunately my problem remains. 

Here's the error message I'm getting:
matlab_error

Three points:
- I've done as you suggested earlier in the previous post and unplugged the anaylsis period so it's definitely an issue with the matlab/UWG. 
- I also manually added the search path for the matlab Runtime in Rhino. Also did't work.  
- In the Dragonfly_Dragonfly src file it sends users to the 64bit of the Mathlab Runtime Compiler. https://github.com/chriswmackey/Dragonfly/blob/master/src/Dragonfly_Dragonfly.py#L1019 But you suggested earlier that the older UWGEngine.exe runs on the 32 bit (I assume UWGEngine was compiled with 32bit). Or is this an error? 

Dragonfly was working for me perfectly on another machine (which I no longer have access to), so maybe it's just my computer somehow...

Anyway, for now I'm at a dead end again. 

S

**Comment by saeranv** [comment]
Okay update, I just tried it with the 64 bit version and this looks better. The problem now is with the epw file being generated.

df_error_64

And this is the uwg folder in the c:\\ladybug folder. It's creating an empty epw file, with a slightly different name:
df_error_642

S

**Comment by chriswmackey** [comment]
@saeranv ,

Yes, sorry for the misinformation earlier in this thread.  The 64-bit version is the one that you want.  I had made a mistake because the UWG has gone through several revisions in the last year and one of them involved transitioning to 64-bit.

Glad that everything is working on your end now and I'll keep you posted when I do a revision to bring Dragonfly up to the latest UWG.

-Chris

**Comment by chriswmackey** [comment]
... Ah wait, I got so excited that we had fixed one problem that I failed to realize that we still have another. What does the resulting epw file look like when you open it in a text editor?

Also, did you delete the C:\ladybug\UWG folder before running the Grasshopper script as I mentioned in the GH Group discussion?

**Comment by saeranv** [comment]
@chriswmackey, hah no problem.  

The new epw file is blank, and yes I did delete the C:\ladybug\UWG folder.

**Comment by chriswmackey** [comment]
@saeranv ,

I have tried to recreate your issue on 3 different machines including office computers with no success (it's working on all of them).  Are you getting the UWG splash page popping up when the UWG runs?
image

Knowing this would at least let me know whether the UWG is starting correctly.  If the splash page is starting up, do you get a lot of lines saying "FATAL ERROR" in the command prompt?

-Chris

**Comment by saeranv** [comment]
@chriswmackey 

Oh man, thanks for sticking with this. I am getting the UWG splash page, and this in the command prompt:

df_1

And then this comes up, and the command prompt shuts down:


df_2

So it is saying that 'MATLAB is exiting because of fatal error'

I dug up the crash report:
[matlab_crash_dump.4020-1.txt](https://github.com/chriswmackey/Dragonfly/files/915491/matlab_crash_dump.4020-1.txt)


Anyway, don't worry if you can't crack this for now. It looks like this is an edge case, that isn't affecting anyone else. I might just have to wait until I can get access on another computer to get DF to work. 

- S

**Comment by chriswmackey** [comment]
@saeranv ,

No need to thank me. You are helping me figure out what the issue is here so that I can better understand what will go wrong when Dragonfly is finally out of beta.

I think I may have found what is causing the problem on your end.  From what I can tell from your text file, your operating systems and processors seem to be of 32-bit architecture (or x86).  This would definitely cause issues with the 64-bit version of the MATLAB compiler as the two would basically be incompatible.  Unfortunately, the version of the UWG that we are using now only works with the 64-bit compiler but @hansukyang might have addressed this in [the most recent version of the UWG](https://github.com/hansukyang/UWG_Matlab/commit/4b9891b0ff26eaf7611fcce067ea521d242e7fc6).

@saeranv , can you confirm that you operating system is 32-bit?  If so, this is the smoking gun that we have been looking for and I'll try to upgrade to the new UWG as soon as I can to see if this fixes it.

-Chris

**Comment by saeranv** [comment]
@chriswmackey,
 
Damn, that's bizarre because I'm using 64-bit OS, x64-based processor (Intel Xeon). I just doubled-checked to make sure I haven't been getting it wrong for years. I'm also using the 64-bit version of Rhino5. 

Which part of the crash report indicates its 32-bit? 

- S

**Comment by chriswmackey** [comment]
@saeranv ,
Perhaps I am wrong here.  The following parts were what made me thing that your processor might be x86 (or 32-bit):
image
Let me take a deeper look later.
-Chris

**Comment by chriswmackey** [comment]
@saeranv ,

I took a closer look and realized that the main error seems to be an "Access Violation", which might indicate that you are not authorized on your machine to use some of the things that the Matlab compiler needs.
image

Do you have admin privileges on your machine and can you think of any feature of your computer that might stop you from using things?  I remember Windows 10 has this really annoying smartscreen application that I had to disable in order to use the computer the way that I wanted.

-Chris

**Comment by saeranv** [comment]
@chriswmackey 

I think we've found the problem. I did some googling about this 'Access violation' and apparently Matlab crashes when using older NVidia drivers: https://www.mathworks.com/matlabcentral/answers/161580-matlab-crashes-when-using-graphics-with-older-nvidia-opengl-drivers

So I followed the fixes suggested in that link: I did a clean install of new drivers, and also changed the profile the driver uses. And it didn't quite work - but it got a lot further then before before getting the 'Fatal Error'. Specifically, it calculates up to this: 

errordf

And then right after I get a series of scrolling 'Fatal Error'. It doesn't crash, and actually completes creating the epw file (with a correctly written title this time). But the epw file itself is riddled with errors and can't be read. 

So I'll have to read into this error more, but it looks like I may need to upgrade my graphics card to get the UWG to work.

-S

**Comment by chriswmackey** [comment]
Great forensic work @saeranv !  I would never have guessed that it was related to the Nvidia drivers.

We are soooo close now.  I have gotten the "Fatal Error" messages in the past and this usually is an issue with the UWG version (not Matlab).  Could you try deleting your C:\ladybug\UWG folder one more time and then opening the Dragonfly script?

If that does not work, could you show me the output of your Dragonfly_Dragonfly?

**Comment by chriswmackey** [comment]
@saeranv ,
There's one more thing that I would suggest, which is to restart your computer. I have found that the Matlab compiler usually needs this after installation and I'd assume a similar situation with the Nvidia drivers.

**Comment by saeranv** [comment]
@chriswmackey , 

So even after deleting the UWG folder, and restarting I'm still getting the scrolling "Fatal Error" messages until it completes the computation (that is, it doesn't abort). The output from Dragonfly_Dragonfly is blank.

However I realized I was still using the default analysisPeriod (which is one year) for my simulation, so I tried plugging in the extreme hot week period, and it worked! So it seems that I'm getting a "Fatal Error" message on certain dates. ExtremeHotWeek and typicalWeek works. The default simulation period, and extremeColdWeek gives me a "Fatal Error"

Have you tried other time periods on your end?  

-S

**Comment by chriswmackey** [comment]
@saeranv ,
Ah, I hadn't checked running the full year in a while.  I was able to recreate your issue on my machine.  Let me get some time to investigate deeper.

**Comment by chriswmackey** [comment]
@saeranv ,
I noticed that the simulation always seems to fail precisely at the 50% mark no matter what the climate file is.  Let me see if I can get to the bottom if this.

**Comment by saeranv** [comment]
@chriswmackey, 

So just to see if I understand: do you think the error has to do with one of the Dragonfly input parameters to runUWG, rather then the UWGEngine itself?

**Comment by chriswmackey** [comment]
@saeranv ,

I was wondering the same thing myself and I just tried to rerun a file for a full year through the UWG that I know I successfully ran ~4 months ago.  It seems that I was able to run this without getting the Fatal Error message, which makes me think that our example is malfunctioning as a result of a bad input that causes the UWG heat flow calculation to get stuck (maybe we have a very thin material that I don't catch?).  Are you able to run this GH file for the full year on your end:
https://drive.google.com/open?id=0Bz2PwDvkjovJUmV3aVVCdHgtYXc

If so, maybe I should just replace the example file on hydra with one that has simpler inputs and will keep the UWG more stable.  At a certain point, I think that we should really translate the UWG to python so that we can fix some of these issues with the UWG.  It's just so difficult to repair these things when none of us can afford Matlab.

Keep me posted,
-Chris

**Comment by saeranv** [comment]
@chriswmackey Confirmed, I can run that file for the full year. 

And I agree that it'd be a lot easier to debug and improve UWG if it was in python, let's convert it.

**Comment by chriswmackey** [comment]
@saeranv ,
I just included you on an email to get the ball rolling on the translation of UWG to python.  I'll update the example file on Hydra soon to something simpler and more stable for the time being.

**Comment by saeranv** [comment]
Sweet, thanks for keeping me in the loop @chriswmackey . Excited to see progress on this :)

**Comment by chriswmackey** [comment]
@saeranv ,
I just wanted to note that we'll continue progress on this bug here:
https://github.com/chriswmackey/UWG_Python/issues/3

**Pull request closed without merging**
